### ISSUE TITLE
Roadmap-0.1.0

### ISSUE THREAD

**Issue by shinGangan** [shinGangan/nuxt-config-website#1]
# Roadmap-0.1.0

- Author: @shinGangan 
- Reviewers:
  - none

### Status

Proposed

### Context

Organize the functions to be supported in `v0.1.0`.

#### docs

- [ ] docs: write README.md

#### feature

- [ ] feat: add `Nuxt Google Fonts`
- [ ] feat: add `Nuxt SEO`
- [ ] feat: add `Nuxt Robots`
- [ ] feat: add `Nuxt Sitemap`

#### Issues

https://github.com/FeaSion/feasion-website/milestone/1

### Consequences

Comment Draft

#### Release Note

- TODO: linked release note
